package webClientGUI;


import java.awt.CardLayout;

/**
 *
 * @author Moiz Mansoor Ali
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPagePanel = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        employeePagePanel = new javax.swing.JPanel();
        employeeTabs = new javax.swing.JTabbedPane();
        createEmployee = new javax.swing.JPanel();
        createEmployee_heading = new javax.swing.JLabel();
        createEmployee_addEmployeeDetails = new javax.swing.JPanel();
        createEmployee_nameText = new javax.swing.JLabel();
        createEmployee_name = new javax.swing.JTextField();
        createEmployee_positionText = new javax.swing.JLabel();
        createEmployee_position = new javax.swing.JTextField();
        createEmployee_usernameText = new javax.swing.JLabel();
        createEmployee_username = new javax.swing.JTextField();
        createEmployee_passwordText = new javax.swing.JLabel();
        createEmployee_password = new javax.swing.JPasswordField();
        createEmployee_retypePasswordText = new javax.swing.JLabel();
        createEmployee_retypePassword = new javax.swing.JPasswordField();
        createEmployee_errorMessage = new javax.swing.JLabel();
        createEmployee_clear = new javax.swing.JButton();
        createEmployee_addEmployee = new javax.swing.JButton();
        editEmployee = new javax.swing.JPanel();
        editEmployee_heading = new javax.swing.JLabel();
        editEmployee_previousEmployee = new javax.swing.JButton();
        editEmployee_nextEmployee = new javax.swing.JButton();
        editEmployee_editEmployeeDetails = new javax.swing.JPanel();
        editEmployee_nameText = new javax.swing.JLabel();
        editEmployee_name = new javax.swing.JTextField();
        editEmployee_positionText = new javax.swing.JLabel();
        editEmployee_position = new javax.swing.JTextField();
        editEmployee_usernameText = new javax.swing.JLabel();
        editEmployee_username = new javax.swing.JTextField();
        editEmplyee_passwordText = new javax.swing.JLabel();
        editEmployee_password = new javax.swing.JPasswordField();
        editEmployee_retypePasswordText = new javax.swing.JLabel();
        editEmployee_retypePassword = new javax.swing.JPasswordField();
        editEmployee_errorMessage = new javax.swing.JLabel();
        editEmployee_saveChanges = new javax.swing.JButton();
        deleteEmployee = new javax.swing.JPanel();
        deleteEmployee_heading = new javax.swing.JLabel();
        deleteEmployee_previousEmployee = new javax.swing.JButton();
        deleteEmployee_nextEmployee = new javax.swing.JButton();
        deleteEmployee_deleteEmployeeDetails = new javax.swing.JPanel();
        deleteEmployee_nameText = new javax.swing.JLabel();
        deleteEmployee_name = new javax.swing.JLabel();
        deleteEmployee_positionText = new javax.swing.JLabel();
        deleteEmployee_position = new javax.swing.JLabel();
        deleteEmployee_usernameText = new javax.swing.JLabel();
        deleteEmployee_username = new javax.swing.JLabel();
        deleteEmployee_errorMessage = new javax.swing.JLabel();
        deleteEmployee_deleteEmployee = new javax.swing.JButton();
        customerListPagePanel = new javax.swing.JPanel();
        customerListScrollPane = new javax.swing.JScrollPane();
        customerListTable = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        customerAccountPagePanel = new javax.swing.JPanel();
        customerTabs = new javax.swing.JTabbedPane();
        createCustomer = new javax.swing.JPanel();
        createCustomer_heading = new javax.swing.JLabel();
        createCustomer_personalDetails = new javax.swing.JPanel();
        createCustomer_nameText = new javax.swing.JLabel();
        createCustomer_name = new javax.swing.JTextField();
        createCustomer_birthDateText = new javax.swing.JLabel();
        createCustomer_birthDate = new javax.swing.JTextField();
        createCustomer_addressText = new javax.swing.JLabel();
        createCustomer_address = new javax.swing.JTextField();
        createCustomer_mobileText = new javax.swing.JLabel();
        createCustomer_mobile = new javax.swing.JTextField();
        createCustomer_emailText = new javax.swing.JLabel();
        createCustomer_email = new javax.swing.JTextField();
        createCustomer_accountDetails = new javax.swing.JPanel();
        createCustomer_accountTypeText = new javax.swing.JLabel();
        createCustomer_accountType = new javax.swing.JTextField();
        createCustomer_accountNumberText = new javax.swing.JLabel();
        createCustomer_accountNumber = new javax.swing.JTextField();
        createCustomer_sortCodeText = new javax.swing.JLabel();
        createCustomer_sortCode = new javax.swing.JTextField();
        createCustomer_balanceText = new javax.swing.JLabel();
        createCustomer_balance = new javax.swing.JTextField();
        createCustomer_cardText = new javax.swing.JLabel();
        createCustomer_card = new javax.swing.JComboBox<>();
        createCustomer_errorMessage = new javax.swing.JLabel();
        createCustomer_clear = new javax.swing.JButton();
        createCustomer_addCustomer = new javax.swing.JButton();
        editCustomer = new javax.swing.JPanel();
        editCustomer_heading = new javax.swing.JLabel();
        editCustomer_previousCustomer = new javax.swing.JButton();
        editCustomer_nextCustomer = new javax.swing.JButton();
        editCustomer_personalDetails = new javax.swing.JPanel();
        editCustomer_nameText = new javax.swing.JLabel();
        editCustomer_name = new javax.swing.JTextField();
        editCustomer_birthDateText = new javax.swing.JLabel();
        editCustomer_birthDate = new javax.swing.JTextField();
        editCustomer_addressText = new javax.swing.JLabel();
        editCustomer_address = new javax.swing.JTextField();
        editCustomer_mobileText = new javax.swing.JLabel();
        editCustomer_mobile = new javax.swing.JTextField();
        editCustomer_emailText = new javax.swing.JLabel();
        editCustomer_email = new javax.swing.JTextField();
        editCustomer_accountDetails = new javax.swing.JPanel();
        editCustomer_accountTypeText = new javax.swing.JLabel();
        editCustomer_accountType = new javax.swing.JTextField();
        editCustomer_accountNumberText = new javax.swing.JLabel();
        editCustomer_accountNumber = new javax.swing.JTextField();
        editCustomer_sortCodeText = new javax.swing.JLabel();
        editCustomer_sortCode = new javax.swing.JTextField();
        editCustomer_balanceText = new javax.swing.JLabel();
        editCustomer_balance = new javax.swing.JTextField();
        editCustomer_cardText = new javax.swing.JLabel();
        editCustomer_card = new javax.swing.JComboBox<>();
        editCustomer_errorMessage = new javax.swing.JLabel();
        editCustomer_saveChanges = new javax.swing.JButton();
        deleteCustomer = new javax.swing.JPanel();
        deleteCustomer_heading = new javax.swing.JLabel();
        deleteCustomer_previousCustomer = new javax.swing.JButton();
        deleteCustomer_nextCustomer = new javax.swing.JButton();
        deleteCustomer_personalDetails = new javax.swing.JPanel();
        deleteCustomer_nameText = new javax.swing.JLabel();
        deleteCustomer_name = new javax.swing.JLabel();
        deleteCustomer_birthDateText = new javax.swing.JLabel();
        deleteCustomer_birthDate = new javax.swing.JLabel();
        deleteCustomer_addressText = new javax.swing.JLabel();
        deleteCustomer_address = new javax.swing.JLabel();
        deleteCustomer_mobileText = new javax.swing.JLabel();
        deleteCustomer_mobile = new javax.swing.JLabel();
        deleteCustomer_emailText = new javax.swing.JLabel();
        deleteCustomer_emial = new javax.swing.JLabel();
        deleteCustomer_accountDetails = new javax.swing.JPanel();
        deleteCustomer_accountTypetext = new javax.swing.JLabel();
        deleteCustomer_accountType = new javax.swing.JLabel();
        deleteCustomer_accountNumberText = new javax.swing.JLabel();
        deleteCustomer_accountNumber = new javax.swing.JLabel();
        deleteCustomer_sortCodeText = new javax.swing.JLabel();
        deleteCustomer_sortCode = new javax.swing.JLabel();
        deleteCustomer_balanceText = new javax.swing.JLabel();
        deleteCustomer_balance = new javax.swing.JLabel();
        deleteCustomer_cardText = new javax.swing.JLabel();
        deleteCustomer_card = new javax.swing.JLabel();
        deleteCustomer_errorMessage = new javax.swing.JLabel();
        deleteCustomer_deleteCustomer = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        logOut = new javax.swing.JMenuItem();
        logOutAndExit = new javax.swing.JMenuItem();
        navigateTo = new javax.swing.JMenu();
        employeePage = new javax.swing.JMenuItem();
        customerListPage = new javax.swing.JMenuItem();
        customerAccountPage = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);

        mainPagePanel.setLayout(new java.awt.CardLayout());

        welcomeLabel.setText("welcome Label");

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        mainPagePanel.add(defaultPanel, "defaultPanel");

        createEmployee_heading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createEmployee_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createEmployee_heading.setText("Create Employee");

        createEmployee_addEmployeeDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Add Employee Details"));

        createEmployee_nameText.setText("Name:");

        createEmployee_positionText.setText("Position:");

        createEmployee_usernameText.setText("Username:");

        createEmployee_passwordText.setText("Password:");

        createEmployee_retypePasswordText.setText("Retype Password:");

        createEmployee_retypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployee_retypePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createEmployee_addEmployeeDetailsLayout = new javax.swing.GroupLayout(createEmployee_addEmployeeDetails);
        createEmployee_addEmployeeDetails.setLayout(createEmployee_addEmployeeDetailsLayout);
        createEmployee_addEmployeeDetailsLayout.setHorizontalGroup(
            createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createEmployee_addEmployeeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createEmployee_nameText)
                    .addComponent(createEmployee_positionText)
                    .addComponent(createEmployee_usernameText)
                    .addComponent(createEmployee_passwordText)
                    .addComponent(createEmployee_retypePasswordText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createEmployee_name)
                    .addComponent(createEmployee_position)
                    .addComponent(createEmployee_username)
                    .addComponent(createEmployee_password)
                    .addComponent(createEmployee_retypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createEmployee_addEmployeeDetailsLayout.setVerticalGroup(
            createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createEmployee_addEmployeeDetailsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployee_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createEmployee_nameText))
                .addGap(18, 18, 18)
                .addGroup(createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployee_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createEmployee_positionText))
                .addGap(18, 18, 18)
                .addGroup(createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployee_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createEmployee_usernameText))
                .addGap(18, 18, 18)
                .addGroup(createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployee_passwordText)
                    .addComponent(createEmployee_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createEmployee_addEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployee_retypePasswordText)
                    .addComponent(createEmployee_retypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        createEmployee_errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        createEmployee_errorMessage.setText("Error Message Displayed Here!");

        createEmployee_clear.setText("Clear");
        createEmployee_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployee_clearActionPerformed(evt);
            }
        });

        createEmployee_addEmployee.setText("Add Employee");
        createEmployee_addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEmployee_addEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createEmployeeLayout = new javax.swing.GroupLayout(createEmployee);
        createEmployee.setLayout(createEmployeeLayout);
        createEmployeeLayout.setHorizontalGroup(
            createEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEmployeeLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(createEmployee_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createEmployee_addEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(createEmployeeLayout.createSequentialGroup()
                        .addComponent(createEmployee_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createEmployee_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createEmployee_addEmployee)))
                .addContainerGap())
        );
        createEmployeeLayout.setVerticalGroup(
            createEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createEmployeeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(createEmployee_heading)
                .addGap(28, 28, 28)
                .addComponent(createEmployee_addEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(createEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createEmployee_addEmployee)
                    .addComponent(createEmployee_clear)
                    .addComponent(createEmployee_errorMessage))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        employeeTabs.addTab("Create Employee", createEmployee);

        editEmployee_heading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editEmployee_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editEmployee_heading.setText("Edit Employee");

        editEmployee_previousEmployee.setText("<<<");

        editEmployee_nextEmployee.setText(">>>");

        editEmployee_editEmployeeDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Edit Employee Details"));

        editEmployee_nameText.setText("Name:");

        editEmployee_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployee_nameActionPerformed(evt);
            }
        });

        editEmployee_positionText.setText("Position:");

        editEmployee_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployee_positionActionPerformed(evt);
            }
        });

        editEmployee_usernameText.setText("Username:");

        editEmplyee_passwordText.setText("Password:");

        editEmployee_retypePasswordText.setText("Retype Password:");

        javax.swing.GroupLayout editEmployee_editEmployeeDetailsLayout = new javax.swing.GroupLayout(editEmployee_editEmployeeDetails);
        editEmployee_editEmployeeDetails.setLayout(editEmployee_editEmployeeDetailsLayout);
        editEmployee_editEmployeeDetailsLayout.setHorizontalGroup(
            editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmployee_editEmployeeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editEmployee_nameText)
                    .addComponent(editEmployee_positionText)
                    .addComponent(editEmployee_usernameText)
                    .addComponent(editEmplyee_passwordText)
                    .addComponent(editEmployee_retypePasswordText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editEmployee_name)
                    .addComponent(editEmployee_position)
                    .addComponent(editEmployee_username)
                    .addComponent(editEmployee_password)
                    .addComponent(editEmployee_retypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editEmployee_editEmployeeDetailsLayout.setVerticalGroup(
            editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmployee_editEmployeeDetailsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployee_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEmployee_nameText))
                .addGap(18, 18, 18)
                .addGroup(editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployee_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEmployee_positionText))
                .addGap(18, 18, 18)
                .addGroup(editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployee_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEmployee_usernameText))
                .addGap(18, 18, 18)
                .addGroup(editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployee_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEmplyee_passwordText))
                .addGap(18, 18, 18)
                .addGroup(editEmployee_editEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployee_retypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEmployee_retypePasswordText))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        editEmployee_errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        editEmployee_errorMessage.setText("Error Message Displayed Here!");

        editEmployee_saveChanges.setText("Save Changes");
        editEmployee_saveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployee_saveChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editEmployeeLayout = new javax.swing.GroupLayout(editEmployee);
        editEmployee.setLayout(editEmployeeLayout);
        editEmployeeLayout.setHorizontalGroup(
            editEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editEmployeeLayout.createSequentialGroup()
                        .addComponent(editEmployee_previousEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editEmployee_nextEmployee))
                    .addComponent(editEmployee_editEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editEmployeeLayout.createSequentialGroup()
                        .addComponent(editEmployee_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editEmployee_saveChanges)))
                .addContainerGap())
            .addGroup(editEmployeeLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(editEmployee_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );
        editEmployeeLayout.setVerticalGroup(
            editEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmployeeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(editEmployee_heading)
                .addGap(18, 18, 18)
                .addGroup(editEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editEmployee_nextEmployee, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editEmployee_previousEmployee, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(editEmployee_editEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployee_saveChanges)
                    .addComponent(editEmployee_errorMessage))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        employeeTabs.addTab("Edit Employee", editEmployee);

        deleteEmployee_heading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteEmployee_heading.setText("Delete Employee");

        deleteEmployee_previousEmployee.setText("<<<");

        deleteEmployee_nextEmployee.setText(">>>");

        deleteEmployee_deleteEmployeeDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Delete Employee Details"));

        deleteEmployee_nameText.setText("Name:");

        deleteEmployee_name.setText("Employee's Name");

        deleteEmployee_positionText.setText("Position:");

        deleteEmployee_position.setText("Employee's Position");

        deleteEmployee_usernameText.setText("Username:");

        deleteEmployee_username.setText("Employee's Username");

        javax.swing.GroupLayout deleteEmployee_deleteEmployeeDetailsLayout = new javax.swing.GroupLayout(deleteEmployee_deleteEmployeeDetails);
        deleteEmployee_deleteEmployeeDetails.setLayout(deleteEmployee_deleteEmployeeDetailsLayout);
        deleteEmployee_deleteEmployeeDetailsLayout.setHorizontalGroup(
            deleteEmployee_deleteEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployee_deleteEmployeeDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteEmployee_deleteEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteEmployee_nameText)
                    .addComponent(deleteEmployee_positionText)
                    .addComponent(deleteEmployee_usernameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deleteEmployee_deleteEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteEmployee_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteEmployee_position, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteEmployee_username))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteEmployee_deleteEmployeeDetailsLayout.setVerticalGroup(
            deleteEmployee_deleteEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployee_deleteEmployeeDetailsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(deleteEmployee_deleteEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEmployee_name)
                    .addComponent(deleteEmployee_nameText))
                .addGap(18, 18, 18)
                .addGroup(deleteEmployee_deleteEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEmployee_position)
                    .addComponent(deleteEmployee_positionText))
                .addGap(18, 18, 18)
                .addGroup(deleteEmployee_deleteEmployeeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEmployee_username)
                    .addComponent(deleteEmployee_usernameText))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        deleteEmployee_errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        deleteEmployee_errorMessage.setText("Error Message Displayed Here!");

        deleteEmployee_deleteEmployee.setText("Delete Employee");

        javax.swing.GroupLayout deleteEmployeeLayout = new javax.swing.GroupLayout(deleteEmployee);
        deleteEmployee.setLayout(deleteEmployeeLayout);
        deleteEmployeeLayout.setHorizontalGroup(
            deleteEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteEmployee_deleteEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteEmployeeLayout.createSequentialGroup()
                        .addComponent(deleteEmployee_previousEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteEmployee_nextEmployee))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteEmployeeLayout.createSequentialGroup()
                        .addComponent(deleteEmployee_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteEmployee_deleteEmployee)))
                .addContainerGap())
            .addGroup(deleteEmployeeLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(deleteEmployee_heading)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        deleteEmployeeLayout.setVerticalGroup(
            deleteEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteEmployeeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(deleteEmployee_heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(deleteEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEmployee_nextEmployee)
                    .addComponent(deleteEmployee_previousEmployee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteEmployee_deleteEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(deleteEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteEmployee_deleteEmployee)
                    .addComponent(deleteEmployee_errorMessage))
                .addGap(211, 211, 211))
        );

        employeeTabs.addTab("Delete Employee", deleteEmployee);

        javax.swing.GroupLayout employeePagePanelLayout = new javax.swing.GroupLayout(employeePagePanel);
        employeePagePanel.setLayout(employeePagePanelLayout);
        employeePagePanelLayout.setHorizontalGroup(
            employeePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeTabs)
        );
        employeePagePanelLayout.setVerticalGroup(
            employeePagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeTabs)
        );

        mainPagePanel.add(employeePagePanel, "employeePagePanel");

        customerListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, ""},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Account Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerListScrollPane.setViewportView(customerListTable);

        refresh.setText("Refresh");

        javax.swing.GroupLayout customerListPagePanelLayout = new javax.swing.GroupLayout(customerListPagePanel);
        customerListPagePanel.setLayout(customerListPagePanelLayout);
        customerListPagePanelLayout.setHorizontalGroup(
            customerListPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerListPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerListPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerListPagePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(refresh)))
                .addContainerGap())
        );
        customerListPagePanelLayout.setVerticalGroup(
            customerListPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerListPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(refresh)
                .addContainerGap())
        );

        mainPagePanel.add(customerListPagePanel, "customerListPagePanel");

        createCustomer_heading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        createCustomer_heading.setText("Add Customer Details");

        createCustomer_personalDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Personal Details"));

        createCustomer_nameText.setText("Name:");

        createCustomer_birthDateText.setText("Birth Date:");

        createCustomer_addressText.setText("Address:");

        createCustomer_mobileText.setText("Mobile:");

        createCustomer_emailText.setText("E-Mail:");

        javax.swing.GroupLayout createCustomer_personalDetailsLayout = new javax.swing.GroupLayout(createCustomer_personalDetails);
        createCustomer_personalDetails.setLayout(createCustomer_personalDetailsLayout);
        createCustomer_personalDetailsLayout.setHorizontalGroup(
            createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomer_personalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createCustomer_nameText)
                    .addComponent(createCustomer_birthDateText)
                    .addComponent(createCustomer_addressText)
                    .addComponent(createCustomer_mobileText)
                    .addComponent(createCustomer_emailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createCustomer_email)
                    .addComponent(createCustomer_name)
                    .addComponent(createCustomer_birthDate)
                    .addComponent(createCustomer_address)
                    .addComponent(createCustomer_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createCustomer_personalDetailsLayout.setVerticalGroup(
            createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomer_personalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_nameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_birthDateText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_addressText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_mobileText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_emailText))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        createCustomer_accountDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Account Details"));

        createCustomer_accountTypeText.setText("Account Type:");

        createCustomer_accountNumberText.setText("Account Number:");

        createCustomer_sortCodeText.setText("Sort Code:");

        createCustomer_balanceText.setText("Balance:");

        createCustomer_cardText.setText("Card:");

        createCustomer_card.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit", "Debit" }));
        createCustomer_card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCustomer_cardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCustomer_accountDetailsLayout = new javax.swing.GroupLayout(createCustomer_accountDetails);
        createCustomer_accountDetails.setLayout(createCustomer_accountDetailsLayout);
        createCustomer_accountDetailsLayout.setHorizontalGroup(
            createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomer_accountDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createCustomer_accountTypeText)
                    .addComponent(createCustomer_accountNumberText)
                    .addComponent(createCustomer_sortCodeText)
                    .addComponent(createCustomer_balanceText)
                    .addComponent(createCustomer_cardText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createCustomer_accountType)
                    .addComponent(createCustomer_accountNumber)
                    .addComponent(createCustomer_sortCode)
                    .addComponent(createCustomer_balance)
                    .addComponent(createCustomer_card, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createCustomer_accountDetailsLayout.setVerticalGroup(
            createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomer_accountDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_accountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_accountTypeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_accountNumberText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_sortCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_sortCodeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createCustomer_balanceText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_cardText)
                    .addComponent(createCustomer_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        createCustomer_errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        createCustomer_errorMessage.setText("Error Message Displayed Here!");

        createCustomer_clear.setText("Clear");

        createCustomer_addCustomer.setText("Add Customer");

        javax.swing.GroupLayout createCustomerLayout = new javax.swing.GroupLayout(createCustomer);
        createCustomer.setLayout(createCustomerLayout);
        createCustomerLayout.setHorizontalGroup(
            createCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createCustomer_accountDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomerLayout.createSequentialGroup()
                        .addComponent(createCustomer_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createCustomer_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createCustomer_addCustomer))
                    .addComponent(createCustomer_personalDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCustomerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createCustomer_heading)
                .addGap(104, 104, 104))
        );
        createCustomerLayout.setVerticalGroup(
            createCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createCustomer_heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createCustomer_personalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createCustomer_accountDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(createCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCustomer_addCustomer)
                    .addComponent(createCustomer_clear)
                    .addComponent(createCustomer_errorMessage))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        customerTabs.addTab("Create Customer", createCustomer);

        editCustomer_heading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editCustomer_heading.setText("Edit Customer Details");

        editCustomer_previousCustomer.setText("<<<");

        editCustomer_nextCustomer.setText(">>>");

        editCustomer_personalDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Personal Details"));

        editCustomer_nameText.setText("Name:");

        editCustomer_birthDateText.setText("Birth Date:");

        editCustomer_addressText.setText("Address:");

        editCustomer_mobileText.setText("Mobile:");

        editCustomer_emailText.setText("E-mail:");

        javax.swing.GroupLayout editCustomer_personalDetailsLayout = new javax.swing.GroupLayout(editCustomer_personalDetails);
        editCustomer_personalDetails.setLayout(editCustomer_personalDetailsLayout);
        editCustomer_personalDetailsLayout.setHorizontalGroup(
            editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomer_personalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editCustomer_nameText)
                    .addComponent(editCustomer_birthDateText)
                    .addComponent(editCustomer_addressText)
                    .addComponent(editCustomer_mobileText)
                    .addComponent(editCustomer_emailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editCustomer_name)
                    .addComponent(editCustomer_birthDate)
                    .addComponent(editCustomer_address)
                    .addComponent(editCustomer_mobile)
                    .addComponent(editCustomer_email, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editCustomer_personalDetailsLayout.setVerticalGroup(
            editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomer_personalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_nameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_birthDateText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_addressText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_mobileText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_emailText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editCustomer_accountDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Account Details"));

        editCustomer_accountTypeText.setText("Account Type:");

        editCustomer_accountNumberText.setText("Account Number:");

        editCustomer_sortCodeText.setText("Sort Code:");

        editCustomer_balanceText.setText("Balance:");

        editCustomer_cardText.setText("Card:");

        editCustomer_card.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit", "Debit" }));

        javax.swing.GroupLayout editCustomer_accountDetailsLayout = new javax.swing.GroupLayout(editCustomer_accountDetails);
        editCustomer_accountDetails.setLayout(editCustomer_accountDetailsLayout);
        editCustomer_accountDetailsLayout.setHorizontalGroup(
            editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomer_accountDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editCustomer_accountTypeText)
                    .addComponent(editCustomer_accountNumberText)
                    .addComponent(editCustomer_sortCodeText)
                    .addComponent(editCustomer_balanceText)
                    .addComponent(editCustomer_cardText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editCustomer_accountType)
                    .addComponent(editCustomer_accountNumber)
                    .addComponent(editCustomer_sortCode)
                    .addComponent(editCustomer_balance)
                    .addComponent(editCustomer_card, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        editCustomer_accountDetailsLayout.setVerticalGroup(
            editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomer_accountDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_accountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_accountTypeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_accountNumberText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_sortCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_sortCodeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer_balanceText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_cardText)
                    .addComponent(editCustomer_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editCustomer_errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        editCustomer_errorMessage.setText("Error Message Displayed Here!");

        editCustomer_saveChanges.setText("Save Changes");
        editCustomer_saveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomer_saveChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editCustomerLayout = new javax.swing.GroupLayout(editCustomer);
        editCustomer.setLayout(editCustomerLayout);
        editCustomerLayout.setHorizontalGroup(
            editCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editCustomer_personalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editCustomer_accountDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(editCustomerLayout.createSequentialGroup()
                        .addComponent(editCustomer_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editCustomer_saveChanges))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCustomerLayout.createSequentialGroup()
                        .addComponent(editCustomer_previousCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editCustomer_nextCustomer)))
                .addContainerGap())
            .addGroup(editCustomerLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(editCustomer_heading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editCustomerLayout.setVerticalGroup(
            editCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editCustomer_heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_nextCustomer)
                    .addComponent(editCustomer_previousCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCustomer_personalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(editCustomer_accountDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCustomer_errorMessage)
                    .addComponent(editCustomer_saveChanges))
                .addContainerGap())
        );

        customerTabs.addTab("Edit Customer", editCustomer);

        deleteCustomer_heading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteCustomer_heading.setText("Delete Customer Details");

        deleteCustomer_previousCustomer.setText("<<<");

        deleteCustomer_nextCustomer.setText(">>>");

        deleteCustomer_personalDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Personal Details"));

        deleteCustomer_nameText.setText("Name:");

        deleteCustomer_name.setText("Customer's Name");

        deleteCustomer_birthDateText.setText("Birth Date:");

        deleteCustomer_birthDate.setText("Customer's Birth Date");

        deleteCustomer_addressText.setText("Address:");

        deleteCustomer_address.setText("Customer's Address");

        deleteCustomer_mobileText.setText("Mobile:");

        deleteCustomer_mobile.setText("Customer's  Mobile");

        deleteCustomer_emailText.setText("E-Mail:");

        deleteCustomer_emial.setText("Customer's E-Mail");

        javax.swing.GroupLayout deleteCustomer_personalDetailsLayout = new javax.swing.GroupLayout(deleteCustomer_personalDetails);
        deleteCustomer_personalDetails.setLayout(deleteCustomer_personalDetailsLayout);
        deleteCustomer_personalDetailsLayout.setHorizontalGroup(
            deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCustomer_personalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteCustomer_nameText)
                    .addComponent(deleteCustomer_birthDateText)
                    .addComponent(deleteCustomer_addressText)
                    .addComponent(deleteCustomer_mobileText)
                    .addComponent(deleteCustomer_emailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteCustomer_emial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_mobile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_birthDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteCustomer_personalDetailsLayout.setVerticalGroup(
            deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCustomer_personalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_nameText)
                    .addComponent(deleteCustomer_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_birthDate)
                    .addComponent(deleteCustomer_birthDateText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_address)
                    .addComponent(deleteCustomer_addressText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_mobile)
                    .addComponent(deleteCustomer_mobileText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_personalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_emial)
                    .addComponent(deleteCustomer_emailText))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        deleteCustomer_accountDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Account Details"));

        deleteCustomer_accountTypetext.setText("Account Type:");

        deleteCustomer_accountType.setText("Customer's Account Type");

        deleteCustomer_accountNumberText.setText("Account Number:");

        deleteCustomer_accountNumber.setText("Customer's Account Number");

        deleteCustomer_sortCodeText.setText("Sort Code:");

        deleteCustomer_sortCode.setText("Customer's Sort Code");

        deleteCustomer_balanceText.setText("Balance:");

        deleteCustomer_balance.setText("Customer's Balance");

        deleteCustomer_cardText.setText("Card:");

        deleteCustomer_card.setText("Customer's Card Type");

        javax.swing.GroupLayout deleteCustomer_accountDetailsLayout = new javax.swing.GroupLayout(deleteCustomer_accountDetails);
        deleteCustomer_accountDetails.setLayout(deleteCustomer_accountDetailsLayout);
        deleteCustomer_accountDetailsLayout.setHorizontalGroup(
            deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCustomer_accountDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteCustomer_accountTypetext)
                    .addComponent(deleteCustomer_accountNumberText)
                    .addComponent(deleteCustomer_sortCodeText)
                    .addComponent(deleteCustomer_balanceText)
                    .addComponent(deleteCustomer_cardText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteCustomer_accountType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_accountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_sortCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_card, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        deleteCustomer_accountDetailsLayout.setVerticalGroup(
            deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCustomer_accountDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_accountType)
                    .addComponent(deleteCustomer_accountTypetext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_accountNumber)
                    .addComponent(deleteCustomer_accountNumberText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_sortCode)
                    .addComponent(deleteCustomer_sortCodeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_balance)
                    .addComponent(deleteCustomer_balanceText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomer_accountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_card)
                    .addComponent(deleteCustomer_cardText))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        deleteCustomer_errorMessage.setForeground(new java.awt.Color(255, 0, 0));
        deleteCustomer_errorMessage.setText("Error Message Displayed Here!");

        deleteCustomer_deleteCustomer.setText("Delete Customer");

        javax.swing.GroupLayout deleteCustomerLayout = new javax.swing.GroupLayout(deleteCustomer);
        deleteCustomer.setLayout(deleteCustomerLayout);
        deleteCustomerLayout.setHorizontalGroup(
            deleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteCustomer_accountDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteCustomer_personalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(deleteCustomerLayout.createSequentialGroup()
                        .addComponent(deleteCustomer_previousCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteCustomer_nextCustomer))
                    .addGroup(deleteCustomerLayout.createSequentialGroup()
                        .addComponent(deleteCustomer_errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCustomer_deleteCustomer)))
                .addContainerGap())
            .addGroup(deleteCustomerLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(deleteCustomer_heading)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteCustomerLayout.setVerticalGroup(
            deleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteCustomer_heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteCustomer_nextCustomer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteCustomer_previousCustomer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteCustomer_personalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteCustomer_accountDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(deleteCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteCustomer_deleteCustomer)
                    .addComponent(deleteCustomer_errorMessage))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        customerTabs.addTab("Delete Customer", deleteCustomer);

        javax.swing.GroupLayout customerAccountPagePanelLayout = new javax.swing.GroupLayout(customerAccountPagePanel);
        customerAccountPagePanel.setLayout(customerAccountPagePanelLayout);
        customerAccountPagePanelLayout.setHorizontalGroup(
            customerAccountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerTabs)
        );
        customerAccountPagePanelLayout.setVerticalGroup(
            customerAccountPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerAccountPagePanelLayout.createSequentialGroup()
                .addComponent(customerTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPagePanel.add(customerAccountPagePanel, "customerAccountPagePanel");

        file.setText("File");

        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        file.add(logOut);

        logOutAndExit.setText("Log Out And Exit");
        logOutAndExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutAndExitActionPerformed(evt);
            }
        });
        file.add(logOutAndExit);

        mainMenuBar.add(file);

        navigateTo.setText("Navigate To");

        employeePage.setText("Employee Page");
        employeePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeePageActionPerformed(evt);
            }
        });
        navigateTo.add(employeePage);

        customerListPage.setText("Customer List Page");
        customerListPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerListPageActionPerformed(evt);
            }
        });
        navigateTo.add(customerListPage);

        customerAccountPage.setText("Customer Account Page");
        customerAccountPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAccountPageActionPerformed(evt);
            }
        });
        navigateTo.add(customerAccountPage);

        mainMenuBar.add(navigateTo);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePageActionPerformed
        CardLayout cardLayout = (CardLayout)mainPagePanel.getLayout();
        cardLayout.show(mainPagePanel, "employeePagePanel");
    }//GEN-LAST:event_employeePageActionPerformed

    private void customerListPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerListPageActionPerformed
        CardLayout cardLayout = (CardLayout)mainPagePanel.getLayout();
        cardLayout.show(mainPagePanel, "customerListPagePanel");
    }//GEN-LAST:event_customerListPageActionPerformed

    private void customerAccountPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAccountPageActionPerformed
        CardLayout cardLayout = (CardLayout)mainPagePanel.getLayout();
        cardLayout.show(mainPagePanel, "customerAccountPagePanel");
    }//GEN-LAST:event_customerAccountPageActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        LoginPage loginPage = new LoginPage();
        loginPage.show();
        this.dispose();
    }//GEN-LAST:event_logOutActionPerformed

    private void logOutAndExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutAndExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logOutAndExitActionPerformed

    private void editEmployee_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployee_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployee_nameActionPerformed

    private void editEmployee_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployee_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployee_positionActionPerformed

    private void createEmployee_retypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployee_retypePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createEmployee_retypePasswordActionPerformed

    private void createCustomer_cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCustomer_cardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createCustomer_cardActionPerformed

    private void editCustomer_saveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomer_saveChangesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCustomer_saveChangesActionPerformed

    private void createEmployee_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployee_clearActionPerformed
        createEmployee_name.setText("");
        createEmployee_position.setText("");
        createEmployee_username.setText("");
        createEmployee_password.setText("");
        createEmployee_retypePassword.setText("");
    }//GEN-LAST:event_createEmployee_clearActionPerformed

    private void createEmployee_addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEmployee_addEmployeeActionPerformed
        String name = createEmployee_name.getText();
        String position = createEmployee_position.getText();
        String username = createEmployee_username.getText();
        String password = new String(createEmployee_password.getPassword());
        String retypePassword = new String(createEmployee_retypePassword.getPassword());
        if(name.equals("") || position.equals("") || username.equals("") || password.equals("") || retypePassword.equals("")){
            createEmployee_errorMessage.setText("Please Fill All The Above Fields!");
        }else if(password.equals(retypePassword)){
            createEmployee_errorMessage.setText("Employee Created!");
        }else{
            createEmployee_errorMessage.setText("The Two Passwords Do Not Match!");
        }
    }//GEN-LAST:event_createEmployee_addEmployeeActionPerformed

    private void editEmployee_saveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployee_saveChangesActionPerformed
        String name = editEmployee_name.getText();
        String position = editEmployee_position.getText();
        String username = editEmployee_username.getText();
        String password = new String(editEmployee_password.getPassword());
        String retypePassword = new String(editEmployee_retypePassword.getPassword());
        if(name.equals("") || position.equals("") || username.equals("") || password.equals("") || retypePassword.equals("")){
            editEmployee_errorMessage.setText("Please Fill All The Above Fields!");
        }else if(password.equals(retypePassword)){
            editEmployee_errorMessage.setText("Changes Saved!");
        }else{
            editEmployee_errorMessage.setText("The Two Passwords Do Not Match!");
        }
    }//GEN-LAST:event_editEmployee_saveChangesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel createCustomer;
    private javax.swing.JPanel createCustomer_accountDetails;
    private javax.swing.JTextField createCustomer_accountNumber;
    private javax.swing.JLabel createCustomer_accountNumberText;
    private javax.swing.JTextField createCustomer_accountType;
    private javax.swing.JLabel createCustomer_accountTypeText;
    private javax.swing.JButton createCustomer_addCustomer;
    private javax.swing.JTextField createCustomer_address;
    private javax.swing.JLabel createCustomer_addressText;
    private javax.swing.JTextField createCustomer_balance;
    private javax.swing.JLabel createCustomer_balanceText;
    private javax.swing.JTextField createCustomer_birthDate;
    private javax.swing.JLabel createCustomer_birthDateText;
    private javax.swing.JComboBox<String> createCustomer_card;
    private javax.swing.JLabel createCustomer_cardText;
    private javax.swing.JButton createCustomer_clear;
    private javax.swing.JTextField createCustomer_email;
    private javax.swing.JLabel createCustomer_emailText;
    private javax.swing.JLabel createCustomer_errorMessage;
    private javax.swing.JLabel createCustomer_heading;
    private javax.swing.JTextField createCustomer_mobile;
    private javax.swing.JLabel createCustomer_mobileText;
    private javax.swing.JTextField createCustomer_name;
    private javax.swing.JLabel createCustomer_nameText;
    private javax.swing.JPanel createCustomer_personalDetails;
    private javax.swing.JTextField createCustomer_sortCode;
    private javax.swing.JLabel createCustomer_sortCodeText;
    private javax.swing.JPanel createEmployee;
    private javax.swing.JButton createEmployee_addEmployee;
    private javax.swing.JPanel createEmployee_addEmployeeDetails;
    private javax.swing.JButton createEmployee_clear;
    private javax.swing.JLabel createEmployee_errorMessage;
    private javax.swing.JLabel createEmployee_heading;
    private javax.swing.JTextField createEmployee_name;
    private javax.swing.JLabel createEmployee_nameText;
    private javax.swing.JPasswordField createEmployee_password;
    private javax.swing.JLabel createEmployee_passwordText;
    private javax.swing.JTextField createEmployee_position;
    private javax.swing.JLabel createEmployee_positionText;
    private javax.swing.JPasswordField createEmployee_retypePassword;
    private javax.swing.JLabel createEmployee_retypePasswordText;
    private javax.swing.JTextField createEmployee_username;
    private javax.swing.JLabel createEmployee_usernameText;
    private javax.swing.JMenuItem customerAccountPage;
    private javax.swing.JPanel customerAccountPagePanel;
    private javax.swing.JMenuItem customerListPage;
    private javax.swing.JPanel customerListPagePanel;
    private javax.swing.JScrollPane customerListScrollPane;
    private javax.swing.JTable customerListTable;
    private javax.swing.JTabbedPane customerTabs;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JPanel deleteCustomer;
    private javax.swing.JPanel deleteCustomer_accountDetails;
    private javax.swing.JLabel deleteCustomer_accountNumber;
    private javax.swing.JLabel deleteCustomer_accountNumberText;
    private javax.swing.JLabel deleteCustomer_accountType;
    private javax.swing.JLabel deleteCustomer_accountTypetext;
    private javax.swing.JLabel deleteCustomer_address;
    private javax.swing.JLabel deleteCustomer_addressText;
    private javax.swing.JLabel deleteCustomer_balance;
    private javax.swing.JLabel deleteCustomer_balanceText;
    private javax.swing.JLabel deleteCustomer_birthDate;
    private javax.swing.JLabel deleteCustomer_birthDateText;
    private javax.swing.JLabel deleteCustomer_card;
    private javax.swing.JLabel deleteCustomer_cardText;
    private javax.swing.JButton deleteCustomer_deleteCustomer;
    private javax.swing.JLabel deleteCustomer_emailText;
    private javax.swing.JLabel deleteCustomer_emial;
    private javax.swing.JLabel deleteCustomer_errorMessage;
    private javax.swing.JLabel deleteCustomer_heading;
    private javax.swing.JLabel deleteCustomer_mobile;
    private javax.swing.JLabel deleteCustomer_mobileText;
    private javax.swing.JLabel deleteCustomer_name;
    private javax.swing.JLabel deleteCustomer_nameText;
    private javax.swing.JButton deleteCustomer_nextCustomer;
    private javax.swing.JPanel deleteCustomer_personalDetails;
    private javax.swing.JButton deleteCustomer_previousCustomer;
    private javax.swing.JLabel deleteCustomer_sortCode;
    private javax.swing.JLabel deleteCustomer_sortCodeText;
    private javax.swing.JPanel deleteEmployee;
    private javax.swing.JButton deleteEmployee_deleteEmployee;
    private javax.swing.JPanel deleteEmployee_deleteEmployeeDetails;
    private javax.swing.JLabel deleteEmployee_errorMessage;
    private javax.swing.JLabel deleteEmployee_heading;
    private javax.swing.JLabel deleteEmployee_name;
    private javax.swing.JLabel deleteEmployee_nameText;
    private javax.swing.JButton deleteEmployee_nextEmployee;
    private javax.swing.JLabel deleteEmployee_position;
    private javax.swing.JLabel deleteEmployee_positionText;
    private javax.swing.JButton deleteEmployee_previousEmployee;
    private javax.swing.JLabel deleteEmployee_username;
    private javax.swing.JLabel deleteEmployee_usernameText;
    private javax.swing.JPanel editCustomer;
    private javax.swing.JPanel editCustomer_accountDetails;
    private javax.swing.JTextField editCustomer_accountNumber;
    private javax.swing.JLabel editCustomer_accountNumberText;
    private javax.swing.JTextField editCustomer_accountType;
    private javax.swing.JLabel editCustomer_accountTypeText;
    private javax.swing.JTextField editCustomer_address;
    private javax.swing.JLabel editCustomer_addressText;
    private javax.swing.JTextField editCustomer_balance;
    private javax.swing.JLabel editCustomer_balanceText;
    private javax.swing.JTextField editCustomer_birthDate;
    private javax.swing.JLabel editCustomer_birthDateText;
    private javax.swing.JComboBox<String> editCustomer_card;
    private javax.swing.JLabel editCustomer_cardText;
    private javax.swing.JTextField editCustomer_email;
    private javax.swing.JLabel editCustomer_emailText;
    private javax.swing.JLabel editCustomer_errorMessage;
    private javax.swing.JLabel editCustomer_heading;
    private javax.swing.JTextField editCustomer_mobile;
    private javax.swing.JLabel editCustomer_mobileText;
    private javax.swing.JTextField editCustomer_name;
    private javax.swing.JLabel editCustomer_nameText;
    private javax.swing.JButton editCustomer_nextCustomer;
    private javax.swing.JPanel editCustomer_personalDetails;
    private javax.swing.JButton editCustomer_previousCustomer;
    private javax.swing.JButton editCustomer_saveChanges;
    private javax.swing.JTextField editCustomer_sortCode;
    private javax.swing.JLabel editCustomer_sortCodeText;
    private javax.swing.JPanel editEmployee;
    private javax.swing.JPanel editEmployee_editEmployeeDetails;
    private javax.swing.JLabel editEmployee_errorMessage;
    private javax.swing.JLabel editEmployee_heading;
    private javax.swing.JTextField editEmployee_name;
    private javax.swing.JLabel editEmployee_nameText;
    private javax.swing.JButton editEmployee_nextEmployee;
    private javax.swing.JPasswordField editEmployee_password;
    private javax.swing.JTextField editEmployee_position;
    private javax.swing.JLabel editEmployee_positionText;
    private javax.swing.JButton editEmployee_previousEmployee;
    private javax.swing.JPasswordField editEmployee_retypePassword;
    private javax.swing.JLabel editEmployee_retypePasswordText;
    private javax.swing.JButton editEmployee_saveChanges;
    private javax.swing.JTextField editEmployee_username;
    private javax.swing.JLabel editEmployee_usernameText;
    private javax.swing.JLabel editEmplyee_passwordText;
    private javax.swing.JMenuItem employeePage;
    private javax.swing.JPanel employeePagePanel;
    private javax.swing.JTabbedPane employeeTabs;
    private javax.swing.JMenu file;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem logOutAndExit;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPagePanel;
    private javax.swing.JMenu navigateTo;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
